### ISSUE TITLE
`pnpm install` fails with ELIFECYCLE

### ISSUE THREAD

**Issue by penberg** [Fredkiss3/gh-next#1]
I am following the installations steps in https://github.com/Fredkiss3/gh-next, but the `pnpm install` step fails with `ELIFECYCLE` as follows:

```console
penberg@vonneumann www % pnpm install

Lockfile is up to date, resolution step is skipped
Packages: +1131
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1131, reused 1131, downloaded 0, added 0, done
node_modules/.pnpm/deasync@0.1.28/node_modules/deasync: Running install script, failed in 44ms (skipped as optional)
node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3: Running install script...
 ELIFECYCLE  Command failed.
```

Installing `node-gyp` solves the problem:

```console
npm install -g node-gyp
```

But I don't understand (1) where is the `better-sqlite3` dependency coming from and (2) why it's not pulling `node-gyp` automatically.

**Comment by Fredkiss3** [comment]
Hello,

I am like on this one I didn’t know also exactly why `better-sqlite3` is required, but i got that error when installing `@libsql/client` maybe it is a dependency of that lib ? 🤔

For the `node-gyp` case I have no idea why It does that 🤷 .

What I usually do to silence these errors is to install with postinstall scripts disabled :

```shell
pnpm install —-ignore-scripts=true
```

**Comment by Fredkiss3** [comment]
I'm going to close this issue as i think it is already fixed by not installing `libsql`

**Comment by Fredkiss3** [comment]
I'm going to close this issue as i think it is already fixed by not installing `libsql`
