### ISSUE TITLE
[✨ feature] Unit tests and e2e tests

### ISSUE THREAD

**Issue by Avi98** [Fredkiss3/gh-next#45]
**Describe the solution you'd like**
Adding unit test and e2e test will ensure proper working application.
- setup vitest 
- setup playwright
- add @testing-library/react for react dom testing
- add CI pipeline to ensure every test passes before merging into base branch

**Describe alternatives you've considered**
non

- [x] Are you willing to make a PR for this ?

**Comment by Avi98** [comment]
@Fredkiss3 I will create a PR for setting up vitest and playwright. I'm also playing to add GitHub action that runs on every PR for running tests.

Firstly, I'll start by creating tests for the home page and all the components used by the home page.
I'm planing to cover components using unit tests and pages with the E2E test.

**Comment by Fredkiss3** [comment]
Thank you very much @Avi98 , i'm eager to see your PR 🤗

**Comment by Fredkiss3** [comment]
We don't believe in tests here 😅 ... 

Not really but for now i don't need tests for this project, thank you for your contribution though
